[package]
name = "rust-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dclimate-banyan = { path = "../dclimate-banyan" }
libipld = "0.14"
csv = "1.2"
